#!/usr/bin/env bash
set -eu
CR=`echo $'\n> '`

echo "Hello eqdock!"

# SELECT EC-CUBE VERSION
setEccubeVersion()
{
  local -a ARRAY=("4.0.0" "4.0.1" "4.0.2" "4.0.3")
  echo -e "インストールしたいEC-CUBEのバージョンを選択してください" 1>&2
  select VAR in "${ARRAY[@]}"
  do
    if [ "$REPLY" -ge 1 ] && [ "$REPLY" -le 4 ]; then
      break
    fi
    echo "1~4で入力してください" 1>&2
  done

  echo "$VAR"
}

setDBKind()
{
  read -ep "使用したいDBを選択してください mysql/postgres [ mysql ] ${CR}" DB_KIND
  while [ "_${DB_KIND}" != "_mysql" ] && [ "_${DB_KIND}" != "_postgres" ]
  do
    if [ -z "$DB_KIND" ]; then
      DB_KIND=mysql
    fi
    if [ "_${DB_KIND}" != "_mysql" ] && [ "_${DB_KIND}" != "_postgres" ]; then
      echo  1>&2
      read -ep "mysqlまたはpostgresで選択してください ${CR}" DB_KIND
    fi
  done

  echo "$DB_KIND"
}

setDBVersion()
{
  local DB_KIND="$1"
  case "$DB_KIND" in
    "mysql" )
      local ARRAY=("5.5" "5.6" "5.7")
      ;;
    "postgres" )
      local ARRAY=("9.2" "9.3" "9.4" "9.5" "9.6" "10")
      ;;
  esac

  local ARRAY_LEN="${#ARRAY[@]}"
  echo -e "インストールしたい${DB_KIND}のバージョンを選択してください" 1>&2
  select VAR in "${ARRAY[@]}"
  do
    if [ "$REPLY" -ge 1 ] && [ "$REPLY" -le $ARRAY_LEN ]; then
      break
    fi
    echo "1~${ARRAY_LEN}で入力してください" 1>&2
  done

  echo "$VAR"
}

setDBName()
{
  local REGEX='^[0-9a-zA-Z\\-\\_]+$'
  read -ep "登録したいDB名を入力してください また文字を消去したい場合はctrl + uを使用してください${CR}" DB_NAME
  while :
  do
    DB_NAME=$(echo "${DB_NAME}" | xargs)
    HAS_SPACE=$(echo "${DB_NAME}" | grep " ")

    if [ -z "$DB_NAME" ]; then
      read -ep "DB名を入力してください ${CR}" DB_NAME
    elif [ -n "$HAS_SPACE" ]; then
      read -ep "DB名に空白は含められません ${CR}" DB_NAME
    elif [[ "$DB_NAME" =~ $REGEX ]]; then
      break
    else
      read -ep "DB名には半角英数字・ハイフン・アンダースコアのみを使用してください${CR}" DB_NAME
    fi
  done

  echo "$DB_NAME"
}

setDBUser()
{
  local REGEX='^[0-9a-zA-Z\\-\\_]+$'
  read -ep "登録したいDBユーザを入力してください また文字を消去したい場合はctrl + uを使用してください${CR}" DB_USER
  while :
  do
    DB_USER=$(echo "${DB_USER}" | xargs)
    HAS_SPACE=$(echo "${DB_USER}" | grep " ")

    if [ -z "$DB_USER" ]; then
      read -ep "DBユーザを入力してください ${CR}" DB_USER
    elif [ -n "$HAS_SPACE" ]; then
      read -ep "DBユーザに空白は含められません ${CR}" DB_USER
    elif [[ "$DB_USER" =~ $REGEX ]]; then
      break
    else
      read -ep "DBユーザには半角英数字・ハイフン・アンダースコアのみを使用してください${CR}" DB_USER
    fi
  done

  echo "$DB_USER"
}

setDBPasswd()
{
  local REGEX='^[!-/]|[0-9a-zA-Z]|[;-@]|[\[-_]|[{-~]+$'
  read -ep "登録したいDBパスワードを入力してください また文字を消去したい場合はctrl + uを使用してください${CR}" DB_PASSWD
  while :
  do
    DB_PASSWD=$(echo "${DB_PASSWD}" | xargs)
    HAS_SPACE=$(echo "${DB_PASSWD}" | grep " ")

    if [ -z "$DB_PASSWD" ]; then
      read -ep "DBパスワードを入力してください ${CR}" DB_PASSWD
    elif [ -n "$HAS_SPACE" ]; then
      read -ep "DBパスワードに空白は含められません ${CR}" DB_PASSWD
    elif [[ "$DB_PASSWD" =~ $REGEX ]]; then
      break
    else
      read -ep "使用できない文字が含まれています もう一度入力してください${CR}" DB_PASSWD
    fi
  done

  echo "$DB_PASSWD"
}

setDBRootPasswd()
{
  local REGEX='^[!-/]|[0-9a-zA-Z]|[;-@]|[\[-_]|[{-~]+$'
  read -ep "登録したいDBrootパスワードを入力してください また文字を消去したい場合はctrl + uを使用してください${CR}" DB_ROOT_PASSWD
  while :
  do
    DB_ROOT_PASSWD=$(echo "${DB_ROOT_PASSWD}" | xargs)
    HAS_SPACE=$(echo "${DB_ROOT_PASSWD}" | grep " ")

    if [ -z "$DB_ROOT_PASSWD" ]; then
      read -ep "DBrootパスワードを入力してください ${CR}" DB_ROOT_PASSWD
    elif [ -n "$HAS_SPACE" ]; then
      read -ep "DBrootパスワードに空白は含められません ${CR}" DB_ROOT_PASSWD
    elif [[ "$DB_ROOT_PASSWD" =~ $REGEX ]]; then
      break
    else
      read -ep "使用できない文字が含まれています もう一度入力してください${CR}" DB_ROOT_PASSWD
    fi
  done

  echo "$DB_ROOT_PASSWD"
}

setPHPVersion()
{
  local ECCUBE_VERSION="$1"
  case "$ECCUBE_VERSION" in
    "4.0.0" | "4.0.1" )
      local ARRAY=("7.1" "7.2")
      ;;
    * )
      local ARRAY=("7.1" "7.2" "7.3")
      ;;
  esac

  local ARRAY_LEN="${#ARRAY[@]}"
  echo -e "インストールしたいPHPのバージョンを選択してください" 1>&2
  select VAR in "${ARRAY[@]}"
  do
    if [ "$REPLY" -ge 1 ] && [ "$REPLY" -le $ARRAY_LEN ]; then
      break
    fi
    echo "1~${ARRAY_LEN}で入力してください" 1>&2
  done

  echo "$VAR"
}

cloneECCUBE()
{
  local ECCUBE_VERSION="$1"
  # カレントディレクトリにeccubeディレクトリが存在しない場合
  if [ ! -d ./eccube ]; then
    mkdir eccube
  fi

  git clone https://github.com/EC-CUBE/ec-cube.git -b "$ECCUBE_VERSION" ./eccube
}


ECCUBE_VERSION=`setEccubeVersion`
echo "$ECCUBE_VERSION"

cloneECCUBE "$ECCUBE_VERSION"

# DB_KIND=`setDBKind`
# echo "$DB_KIND"

# DB_VERSION=`setDBVersion "${DB_KIND}"`
# echo "$DB_VERSION"

# DB_NAME=`setDBName`
# echo "$DB_NAME"

# DB_USER=`setDBUser`
# echo "$DB_USER"

# DB_PASSWD=`setDBPasswd`
# echo "$DB_PASSWD"

# if [ "_${DB_KIND}" = "mysql"]; then
#   DB_PASSWD=`setDBPasswd`
#   echo "$DB_PASSWD"
# fi

# PHP_VERSION=`setPHPVersion "${ECCUBE_VERSION}"`
# echo "$PHP_VERSION"
